Repository layer5io/getnighthawk, pull requests merged in 2020-08, with the labels that each got.

#3 Update README.md
  README.md
Labels: area/docs

#9 feat: Initialise nighthawk-go api
  api/nighthawk.go
  cmd/main.go
  go.mod
  go.sum
Labels: area/ci, area/performance, component/api, kind/feature

#12 feat: Restructure nighthawk api to resolve conflict with wrk2
  apinighthawk/nighthawk.go
  cmd/main.go
Labels: area/performance, kind/enhancement
